### ISSUE TITLE
言語何にするか問題

### ISSUE THREAD

**Issue by kentama7** [bancha-project/bancha-library#1]
バックエンド

- Rust
- Go
- JS
- Kotlin
- Python
- Ruby
- etc...

**Comment by kentama7** [comment]
@enmanji 何がいいと思いますか？

**Comment by ahyaemon** [comment]
react admin でちょっと試した奴があります
フロントもバックもjsで

**Comment by ahyaemon** [comment]
https://github.com/shutarou-iijima/react-admin-sample

**Comment by kentama7** [comment]
Ktorとか？

**Comment by ahyaemon** [comment]
rustだとactix webってやつですね

**Comment by kentama7** [comment]
バックエンドは安定のKotlin + Micronautにしました。
